# -*- coding: utf-8 -*-
"""GEDI_footprint.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/17Z8PzpN8XXqJzvMnQllsXPExNHiJIn1d
"""

#------------ Pip Install ------------------------------------------------------
!pip install earthaccess h5py numpy pandas geopandas shapely -q

#------------ imports ----------------------------------------------------------
import earthaccess
import h5py
import numpy as np
import pandas as pd
import geopandas as gpd
from shapely.geometry import Point
import datetime
import os

# ---------- Login to NASA Earthdata -------------------------------------------
# prompts for NASA Earthdata username and password
earthaccess.login()

# -------- Insert coordinates for area of interest -----------------------------
LAT_MIN, LAT_MAX = 35.309, 35.312
LON_MIN, LON_MAX = -120.664, -120.657

# ---------- Search for GEDI granules over area of interest --------------------
print('Searching for GEDI granules...')
results = earthaccess.search_data(
    short_name='GEDI02_A',
    version='002',
    bounding_box=(LON_MIN, LAT_MIN, LON_MAX, LAT_MAX)
)
print(f'Found {len(results)} granules covering your arboretum')

# --- Stream each granule and extract shots (~20 min) --------------------------
for granule in results:
    filename = granule['meta']['native-id']
    print(f'\nProcessing: {filename}')

    try:
        # Stream the file directly — no download needed
        files = earthaccess.open([granule])
        h5file = h5py.File(files[0], 'r')
        beams = [k for k in h5file.keys() if k.startswith('BEAM')]

        for beam in beams:
            try:
                lat = h5file[beam]['lat_lowestmode'][:]
                lon = h5file[beam]['lon_lowestmode'][:]

                # Filter to arboretum bounding box
                mask = (
                    (lat >= LAT_MIN) & (lat <= LAT_MAX) &
                    (lon >= LON_MIN) & (lon <= LON_MAX)
                )

                if mask.sum() == 0:
                    continue

                print(f'  {beam}: {mask.sum()} shots in arboretum')

                rh = h5file[beam]['rh'][mask]

                # Date from filename
                try:
                    year = int(filename[9:13])
                    doy  = int(filename[13:16])
                    date = datetime.datetime(year, 1, 1) + datetime.timedelta(doy - 1)
                    date_str = date.strftime('%Y-%m-%d')
                except:
                    date_str = 'unknown'

                shot_data = {
                    'filename':     filename,
                    'beam':         beam,
                    'date':         date_str,
                    'lat':          lat[mask],
                    'lon':          lon[mask],
                    'rh25':         rh[:, 25],
                    'rh50':         rh[:, 50],
                    'rh75':         rh[:, 75],
                    'rh98':         rh[:, 98], #relative height at 98th percentile (top of forest canopy height in m)
                    'sensitivity':  h5file[beam]['sensitivity'][mask], #how well detected ground return through the canopy, ranges from 0 to 1
                                                                        #0.9 - 1.0 → excellent — laser punched through canopy cleanly and found ground
                    'quality_flag': h5file[beam]['quality_flag'][mask],
                    'degrade_flag': h5file[beam]['degrade_flag'][mask],
                    'shot_number':  h5file[beam]['shot_number'][mask].astype(str),
                }

                all_shots.append(pd.DataFrame(shot_data))

            except KeyError as e:
                print(f'  Skipping {beam} — missing field: {e}')
                continue

        h5file.close()

    except Exception as e:
        print(f'  Error: {e}')
        continue

# ------------- Combine all shots ----------------------------------------------
if len(all_shots) == 0:
    print('\nNo shots found in arboretum area')
else:
    combined = pd.concat(all_shots, ignore_index=True)
    print(f'\nTotal shots found: {len(combined)}')

    # Filter to high quality shots only
    quality = combined[
        (combined['quality_flag'] == 1) &
        (combined['degrade_flag'] == 0)
    ].copy()
    print(f'High quality shots: {len(quality)}')
    print(quality[['date', 'beam', 'lat', 'lon', 'rh98', 'sensitivity']].to_string())

# - Save to Google Drive, edit according to own drive folders / file names -
    from google.colab import drive
    drive.mount('/content/drive')

    output_folder = '/content/drive/My Drive/GEDI_Arboretum'
    os.makedirs(output_folder, exist_ok=True)

    # Save CSV
    csv_path = os.path.join(output_folder, 'gedi_arboretum_shots.csv')
    quality.to_csv(csv_path, index=False)
    print(f'\nCSV saved to Google Drive: {csv_path}')

    # Save GeoJSON
    geometry = [Point(lon, lat) for lon, lat in zip(quality['lon'], quality['lat'])]
    gdf = gpd.GeoDataFrame(quality, geometry=geometry, crs='EPSG:4326')
    geojson_path = os.path.join(output_folder, 'gedi_arboretum_shots.geojson')
    gdf.to_file(geojson_path, driver='GeoJSON')
    print(f'GeoJSON saved to Google Drive: {geojson_path}')

    print('\nDone! Download the GeoJSON from Google Drive and load into QGIS.')

# ------ Diagnostic: why were shots rejected? ----------------------------------

all_shots_unfiltered = []

for granule in results:
    filename = granule['meta']['native-id']

    try:
        files = earthaccess.open([granule])
        h5file = h5py.File(files[0], 'r')
        beams = [k for k in h5file.keys() if k.startswith('BEAM')]

        for beam in beams:
            try:
                lat = h5file[beam]['lat_lowestmode'][:]
                lon = h5file[beam]['lon_lowestmode'][:]

                mask = (
                    (lat >= LAT_MIN) & (lat <= LAT_MAX) &
                    (lon >= LON_MIN) & (lon <= LON_MAX)
                )

                if mask.sum() == 0:
                    continue

                quality_flag = h5file[beam]['quality_flag'][mask]
                degrade_flag = h5file[beam]['degrade_flag'][mask]
                sensitivity  = h5file[beam]['sensitivity'][mask]

                # Date from filename
                try:
                    year = int(filename[9:13])
                    doy  = int(filename[13:16])
                    date = datetime.datetime(year, 1, 1) + datetime.timedelta(doy - 1)
                    date_str = date.strftime('%Y-%m-%d')
                except:
                    date_str = 'unknown'

                for i in range(mask.sum()):
                    all_shots_unfiltered.append({
                        'filename':     filename,
                        'beam':         beam,
                        'date':         date_str,
                        'lat':          lat[mask][i],
                        'lon':          lon[mask][i],
                        'quality_flag': quality_flag[i],
                        'degrade_flag': degrade_flag[i],
                        'sensitivity':  sensitivity[i],
                        'rejected':     quality_flag[i] != 1 or degrade_flag[i] != 0
                    })

            except KeyError as e:
                continue

        h5file.close()

    except Exception as e:
        print(f'Error: {e}')
        continue

# ── Summary ───────────────────────────────────────────────────────────────────
df_all = pd.DataFrame(all_shots_unfiltered)

print(f'Total shots in bounding box: {len(df_all)}')
print(f'Accepted (quality=1, degrade=0): {len(df_all[~df_all["rejected"]])}')
print(f'Rejected: {len(df_all[df_all["rejected"]])}')
print()
print('Rejection breakdown:')
print(f'  quality_flag = 0: {len(df_all[df_all["quality_flag"] == 0])}')
print(f'  degrade_flag != 0: {len(df_all[df_all["degrade_flag"] != 0])}')
print()
print('Rejected shots by date and beam:')
rejected = df_all[df_all['rejected']]
print(rejected[['date', 'beam', 'lat', 'lon', 'quality_flag', 'degrade_flag', 'sensitivity']].to_string())